Temp file vulnerability remediation DRAFT
openrewrite/rewrite-java-security pull request #14
Opened 2022-02-04 21:01 UTC by pway99

2022-02-04 21:23 UTC, pway99 commented
Thanks @JLLeitschuh!  Just pushed some changes to the `TempFileVulnerabilityTest`

2022-02-04 22:03 UTC, JLLeitschuh commented on src/test/kotlin/org/openrewrite/java/security/SecureTempFileCreationTest.kt
> +                    Files.createFile(tempDirChild, PosixFilePermissions.asFileAttribute(EnumSet.of(PosixFilePermission.OWNER_READ, PosixFilePermission.OWNER_WRITE)));
Missing import for EnumSet

2022-02-04 22:07 UTC, JLLeitschuh requested changes

2022-02-04 22:07 UTC, JLLeitschuh commented on src/test/kotlin/org/openrewrite/java/security/TempFileVulnerabilityRemediationTest.kt
> +                    Files.createTempDirectory(tempDirChild.toPath(), UUID.randomUUID().toString()).toFile();
Needs posix permissions setting here

2022-02-04 22:07 UTC, JLLeitschuh commented on src/test/kotlin/org/openrewrite/java/security/TempFileVulnerabilityRemediationTest.kt
> +                            PosixFilePermissions.asFileAttribute(EnumSet.of(PosixFilePermission.OWNER_READ, PosixFilePermission.OWNER_WRITE))
Missing import for `EnumSet`

2022-02-04 22:07 UTC, JLLeitschuh commented on src/test/kotlin/org/openrewrite/java/security/TempFileVulnerabilityRemediationTest.kt
> +                    } catch (IOException e) {
Missing import for `IoException`

2022-02-04 22:07 UTC, JLLeitschuh commented on src/test/kotlin/org/openrewrite/java/security/TempFileVulnerabilityRemediationTest.kt
> +                    } catch (IOException e) {
Missing import for `IOException`

2022-02-04 22:07 UTC, JLLeitschuh commented on src/test/kotlin/org/openrewrite/java/security/TempFileVulnerabilityRemediationTest.kt
> +                    Files.createFile(tempSafe, PosixFilePermissions.asFileAttribute(EnumSet.of(PosixFilePermission.OWNER_READ, PosixFilePermission.OWNER_WRITE)));
Missing import for `EnumSet`

2022-02-04 22:07 UTC, JLLeitschuh commented on src/test/kotlin/org/openrewrite/java/security/TempFileVulnerabilityRemediationTest.kt
> +                    Files.createFile(tempSafe1, PosixFilePermissions.asFileAttribute(EnumSet.of(PosixFilePermission.OWNER_READ, PosixFilePermission.OWNER_WRITE)));
Missing import for `EnumSet`

2022-02-04 22:07 UTC, JLLeitschuh commented on src/test/kotlin/org/openrewrite/java/security/TempFileVulnerabilityRemediationTest.kt
> +                    Files.createFile(tempDirChild, PosixFilePermissions.asFileAttribute(EnumSet.of(PosixFilePermission.OWNER_READ, PosixFilePermission.OWNER_WRITE)));
Missing import for `EnumSet`

2022-02-04 22:07 UTC, JLLeitschuh commented on src/test/kotlin/org/openrewrite/java/security/TempFileVulnerabilityRemediationTest.kt
> +                        EnumSet.of(PosixFilePermission.OWNER_READ, PosixFilePermission.OWNER_WRITE))
Missing import for `EnumSet`

2022-02-07 18:05 UTC, JLLeitschuh commented on src/test/kotlin/org/openrewrite/java/security/TempFileVulnerabilityRemediationTest.kt
> +                        throw new UncheckedIOException(e);
Is there value in adding an exception message here in general? I'm on the fence, but some static code analysis tools like rethrown exceptions to add more information.

2022-02-07 21:11 UTC, pway99 commented on src/test/kotlin/org/openrewrite/java/security/TempFileVulnerabilityRemediationTest.kt
> +                        throw new UncheckedIOException(e);
The only value I am aware of is preventing static analysis warnings.  I usually opt for the simplest solution and was not thinking about static code analysis.  I will replace the message with my next commit. Thanks!

2022-02-09 18:48 UTC, pway99 commented on src/test/kotlin/org/openrewrite/java/security/TempFileVulnerabilityRemediationTest.kt
> +                    Files.createDirectories(tempDirChild.toPath(), PosixFilePermissions.asFileAttribute(EnumSet.of(PosixFilePermission.OWNER_READ, PosixFilePermission.OWNER_WRITE)));
@JLLeitschuh looking at
looking at [Files#createDirectories](https://docs.oracle.com/javase/7/docs/api/java/nio/file/Files.html#createDirectories(java.nio.file.Path,%20java.nio.file.attribute.FileAttribute...))
> an exception is not thrown if the directory could not be created because it already exists

should this remediation also be checking that the file does not exist prior to creating the directories?

2022-02-09 20:57 UTC, JLLeitschuh commented on src/test/kotlin/org/openrewrite/java/security/TempFileVulnerabilityRemediationTest.kt
> +                    Files.createDirectories(tempDirChild.toPath(), PosixFilePermissions.asFileAttribute(EnumSet.of(PosixFilePermission.OWNER_READ, PosixFilePermission.OWNER_WRITE)));
If you are checking if it already exists, you should also be checking if the permissions are correctly set. Otherwise, if the file already exists, it could exist because an attacker already created it with wider permissions.

2022-04-26 19:15 UTC, closed without merging